spring:
  application:
    name: zlive-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:user-db-sharding.yaml
    hikari:
      pool-name: zjj-user-pool
      minimum-idle: 150
      maximum-pool-size: 300
#      connection-init-sql: select 1
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: 118.89.68.42
      password: 3FKrphvDRZoAPuqqq5gh
      lettuce:
        pool:
          max-active: 50
          min-idle: 10
          max-idle: 20
      database: 2
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://localhost:8848?namespace=9fabb905-ceb0-4069-9434-ec1bbd595a64&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9091
my:
  rmq:
    producer:
      nameSrv: 127.0.0.1:9876
      groupName: ${spring.application.name}
      retryTimes: 3
      sendTimeOut: 3000
    consumer:
      nameSrv: 127.0.0.1:9876
      groupName: ${spring.application.name}